__object__:
  path: depth_anything_3.model.da3
  name: DepthAnything3Net
  args: as_params

# use the original DinoV2 wrapper
net:
  __object__:
    path: depth_anything_3.model.dinov2.dinov2
    name: DinoV2
    args: as_params

  name: vitb
  out_layers: [5, 7, 9, 11]
  alt_start: 4
  qknorm_start: 4
  rope_start: 4
  cat_token: True

# DualDPT head
head:
  __object__:
    path: depth_anything_3.model.dualdpt
    name: DualDPT
    args: as_params

  dim_in: &head_dim_in 1536
  output_dim: 2
  features: &head_features 128
  out_channels: &head_out_channels [96, 192, 384, 768]
  activation: "exp"
  head_names: ["depth", "ray"]




# # DPT head with reuse dualDPT pre-trained model--achieve exact the same depth estimated as dualDPT
# head:
#   __object__:
#     path: depth_anything_3.model.dpt #depth_anything_3.model.dualdpt
#     name: DPT #DualDPT
#     args: as_params

#   # below param setting enables loading depth_dpt from pretrained dualDPT
#   dim_in: &head_dim_in 1536
#   output_dim: 2
#   norm_type: "layer"
#   pos_embed: True
#   activation: "exp"
#   head_name: "depth"


#   # below param enable train naive depth-only DPT from scratch
#   # dim_in: &head_dim_in 768 # as cat_token is False
#   # output_dim: 2
#   # norm_type: "idt"
#   # pos_embed: False

#   features: &head_features 128
#   out_channels: &head_out_channels [96, 192, 384, 768]
#   use_sky_head: False
