__object__:
  path: networks
  name: EndoDepthAnything3Net
  args: as_params

# LoRA configuration
lora_type: "lora"
# lora_type: "dvlora"
# lora_type: "none"
lora_r: 4

dino_resize_hw:
  - 224
  - 280
ref_view_strategy: "first"

# dino_resize_hw:
# ref_view_strategy: "saddle_balanced"

net:
  __object__:
    path: networks
    name: EndoDinoVisionTransformer
    args: as_params
  
  # vit-Base setting up
  ffn_layer: "mlp"
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4.0
  num_register_tokens: 0

  alt_start: 4
  qknorm_start: 4
  rope_start: 4
  cat_token: True
  # used for extract DPT input for depth estimation
  out_layers: [5, 7, 9, 11] # default in DA3
  # out_layers: [8, 9, 10, 11] # endoDAC style

  # residual_block_indexes: [2, 5, 8, 11] # endodac
  # global layers: 5, 7, 9, 11
  # endo_da3: avoid add res on global layers; only doable if temporal_dim S is 1
  # residual_block_indexes: [4, 6, 8, 10] 
  residual_block_indexes: []

  # dino_resize_hw: actual input image size after resizing (used for residual block patch dimensions)
  # If not specified, falls back to img_size
  dino_resize_hw: [224, 280]


head:
  __object__:
    path: depth_anything_3.model.dualdpt
    name: DualDPT
    args: as_params

  dim_in: &head_dim_in 1536
  output_dim: 2
  features: &head_features 128
  out_channels: &head_out_channels [96, 192, 384, 768]
  # activation: "exp"
  # head_names: ["depth", "depth_conf"]
  
  activation: "sigmoid"
  head_names: ["disp", "depth_conf"]



cam_enc:
  __object__:
    path: depth_anything_3.model.cam_enc
    name: CameraEnc
    args: as_params

  dim_out: 768

cam_dec:
  __object__:
    path: networks
    name: EndoCameraDec
    args: as_params

  dim_in: 1536
  # rot_representation: "euler"
  # rot_representation: "quat"
  # rot_representation: "6D"

  rot_representation: "quat_xyzw"
  # rot_representation: "9D"
  # rot_representation: "angle_axis"
  rot_scale_factor: 0.01
  trans_scale_factor: 0.01
  explicit_bias_init_6d9d: True
